### ISSUE TITLE
Nuoroda į VII skirsnį README.md faile neveikia dėl fragmento kartojimo.

### ISSUE THREAD

**Issue by SlexBi** [Lietuvos-Respublika/Lietuvos-Respublikos-Konstitucija#4]
Turbūt nuoroda turi būti 07%20Lietuvos%20Respublikos%20Vyriausybė.md#vii-skirsnis

**Comment by Gitanas-Nauseda** [comment]
Ačiū už pastebėjimą. Klaida pataisyta ir jau master branch'e!
